apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - database-settings.yml
  - registration-postgres.yml
  - worker-postgres.yml
  - migrations.yml
  - api.yml
  - rabbitmq.yml
  - kafka.yml
  - numbering-grpc.yml
  - worker.yml
  - outbox-publisher.yml
  - kafka-outbox-publisher.yml
  - registration-status-updater.yml