apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distributed-workflow

resources:
  - namespace.yml
  - database-settings.yml
  - registration-postgres.yml
  - worker-postgres.yml
  - migrations.yml
  - api.yml
  - rabbitmq.yml
  - kafka.yml
  - numbering-grpc.yml
  - worker.yml
  - outbox-publisher.yml
  - kafka-outbox-publisher.yml
  - registration-status-updater.yml

configMapGenerator:
  - name: rabbitmq-config
    files:
      - enabled_plugins=rabbitmq/enabled_plugins
      - rabbitmq.conf=rabbitmq/rabbitmq.conf
      - definitions.json=rabbitmq/definitions.json